---
- hosts: docker
  tasks:
        - name: stop container
          command: docker stop regapp-server
          ignore_errors: yes
        - name: remove container
          command: docker container rm regapp-server
          ignore_errors: yes
        - name: remove image
          command: docker image rm nahid787/regapp:latest
          ignore_errors: yes
        - name: create container
          command: docker container run -d --name regapp-server -p 8082:8080 nahid787/regapp:latest
